name: "AI Visual Testing"
description: "Detects UI changes in PRs with AI-powered visual testing"
author: "Joao Garin"
branding:
  icon: "eye"
  color: "purple"
inputs:
  base-url:
    description: "URL of the baseline site (e.g., staging)"
    required: true
  pr-url:
    description: "URL of the PR deployment"
    required: true
  threshold:
    description: "Diff sensitivity (0-1, lower = stricter)"
    required: false
    default: "0.1"

secrets:
  OPENAI_API_KEY:
    description: "OpenAI API key for the agent"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install
      shell: bash

    - name: Install Playwright
      working-directory: ${{ github.action_path }}
      run: |
        npm install -g @playwright/mcp@latest playwright@latest
        npx playwright install --with-deps chromium
        npx playwright install-deps chromium
      shell: bash

    - name: Start MCP Server with Debug Mode
      working-directory: ${{ github.action_path }}
      run: |
        echo "Starting MCP Server..."
        DEBUG=pw:mcp* npx @playwright/mcp@latest --port 8931 &
        echo "Waiting for MCP server to start..."
        sleep 15  # Give the server more time to start and initialize
        echo "Checking if MCP server is running..."
        curl -s http://localhost:8931/health || echo "MCP server not responding to health check"
      shell: bash

    - name: Run URL comparison
      working-directory: ${{ github.action_path }}
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
      run: |
        python scripts/run_agent.py \
          --base-url "${{ inputs.base-url }}" \
          --pr-url "${{ inputs.pr-url }}"
      shell: bash

    - name: Stop MCP Server
      working-directory: ${{ github.action_path }}
      run: |
        pkill -f "@playwright/mcp" || true
      shell: bash
