name: "AI Visual Testing"
description: "Detects UI changes in PRs with AI-powered visual testing"
author: "Joao Garin"
branding:
  icon: "eye"
  color: "purple"
inputs:
  base-url:
    description: "URL of the baseline site (e.g., staging)"
    required: true
  pr-url:
    description: "URL of the PR deployment"
    required: true
  pages:
    description: "JSON array of page paths to test (e.g., ['/', '/about', '/contact']). If not provided, only the homepage is tested."
    required: false
  threshold:
    description: "Diff sensitivity (0-1, lower = stricter)"
    required: false
    default: "0.1"
  bruni-token:
    description: "Token for sending reports to Bruni API"
    required: false
  bruni-api-url:
    description: "URL for the Bruni API endpoint"
    required: false
    default: "https://bruniai-app.vercel.app/api/tests"

secrets:
  OPENAI_API_KEY:
    description: "OpenAI API key for the agent"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      run: |
        npm install
      shell: bash

    - name: Install Playwright
      working-directory: ${{ github.action_path }}
      run: |
        npx playwright install --with-deps chromium
        npx playwright install-deps chromium
      shell: bash

    - name: Start MCP Server
      working-directory: ${{ github.action_path }}
      run: |
        npx @playwright/mcp@latest --port 8931 &
        sleep 5  # Give the server time to start
      shell: bash

    - name: Run URL comparison
      working-directory: ${{ github.action_path }}
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
        PYTHONPATH: ${{ github.action_path }}
      run: |
        node dist/index.js \
          --base-url "${{ inputs.base-url }}" \
          --pr-url "${{ inputs.pr-url }}" \
          --pages "${{ inputs.pages }}" \
          --bruni-token "${{ inputs.bruni-token }}" \
          --bruni-api-url "${{ inputs.bruni-api-url }}"
      shell: bash

    - name: Stop MCP Server
      working-directory: ${{ github.action_path }}
      run: |
        pkill -f "@playwright/mcp" || true
      shell: bash
